[package]
name = "sparrow"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14" }

ron = "0.8.1"
serde = "1.0.202"
serde_json = "1.0.117"
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"
